apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.service.metadata.labels.product }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.service.metadata.labels.product }}
data:
  ConnectionStrings__DefaultConnection: "Host={{ .Values.db.host }};Port={{ .Values.db.port }};Database={{ .Values.db.name }};Username={{ .Values.db.user }};Password=postgres"