apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.metadata.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.service.metadata.labels.product }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.metadata.labels.product }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.metadata.labels.product }}
    spec:
      containers:
        - name: {{ .Values.service.metadata.name }}
          image: {{ .Values.imageName }}
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: {{ .Values.service.metadata.labels.product }}-config
          ports:
              - containerPort: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadata.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.service.metadata.labels.product }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}