apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.metadata.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.service.metadata.labels.product }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.metadata.labels.product }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.metadata.labels.product }}
    spec:
      containers:
        - name: {{ .Values.service.metadata.name }}
          image: {{ .Values.imageName }}
          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadata.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.service.metadata.labels.product }}
  ports:
    - port: 5432
      targetPort: 5432