apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.metadata.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.service.metadata.labels.product }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.metadata.labels.product }}
  template:
    metadata:
      labels:
        app: {{ .Values.service.metadata.labels.product }}
    spec:
      containers:
        - name: {{ .Values.service.metadata.name }}
          image: {{ .Values.imageName }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.metadata.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.service.metadata.labels.product }}
  ports:
    - port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.global.namespace | default "customer1" }}.localhost
      http:
        paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: {{ .Values.service.metadata.name }}
                  port:
                    number: {{ .Values.port }}