imageName: grpc_order_app-order-service:latest
service:
  metadata:
    name: order-service
    labels:
      product: order-service
grpc:
  port: 5201
db:
  host: db
  port: 5432
  name: ordersdb
  user: postgres